Page/welcome page
cstruchevs/Devico_Project_Client pull request #13
Opened 2022-05-04 13:51 UTC by ntnshpig

2022-05-04 14:04 UTC, VolodymyrDevico requested changes

2022-05-04 14:04 UTC, VolodymyrDevico commented on src/components/WelcomePageComponents/NewsSection/NewsSection.jsx
> +  if (matchSm) {
useMemo(() => {
  if(matchSm) {
    return 1
  }
  
  ...
}, [matchSm , matchMd])

2022-05-04 14:04 UTC, VolodymyrDevico commented on src/components/WelcomePageComponents/NewsSection/NewsSection.jsx
> +  const next = () => {
useCallback

2022-05-04 14:04 UTC, VolodymyrDevico commented on src/components/WelcomePageComponents/NewsSection/NewsSection.jsx
> +      <Box width={'100%'} marginTop={'20px'}>
width="100%"

2022-05-05 12:06 UTC, turchin-aa approved these changes

2022-05-05 12:17 UTC, cstruchevs approved these changes

2022-05-05 12:17 UTC, merged