Feature/auth
cstruchevs/Devico_Project_Client pull request #5
Opened 2022-04-25 16:13 UTC by ntnshpig

2022-04-25 16:31 UTC, VolodymyrDevico commented on src/components/Auth/SignInModal.tsx
> +const phoneRegex: RegExp =
Move to constants

2022-04-25 16:31 UTC, VolodymyrDevico commented on src/components/Auth/SignInModal.tsx
> +  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
useCallback

2022-04-25 16:31 UTC, VolodymyrDevico commented on src/components/Auth/SignInModal.tsx
> +  const toggleHandler = () => {
useMemo

2022-04-25 16:31 UTC, VolodymyrDevico commented on src/components/Auth/SignInModal.tsx
> +    if (regCartIsShown) dispatch(uiActions.toggleReg());
Don't write inline

2022-04-25 16:31 UTC, VolodymyrDevico commented on src/components/Auth/SignInModal.tsx
> +          sx={{ margin: "auto" }}
Is it possible to move to JSS?

2022-04-25 16:31 UTC, VolodymyrDevico commented on src/components/Auth/SignInModal.tsx
> +                  {...register("email")}
Is it possible to avoid this?

2022-04-25 16:31 UTC, VolodymyrDevico commented on src/components/Auth/SignUpModal.tsx
> +              {regCartIsShown && (
Better use ternary expression

2022-04-25 16:31 UTC, VolodymyrDevico commented on src/components/CongratModule.tsx/CongratModule.tsx
> +
useless transition

2022-04-25 16:31 UTC, VolodymyrDevico commented on src/components/Auth/SignUpModal.tsx
> +export default Auth;
memo

2022-04-25 16:31 UTC, VolodymyrDevico commented on src/components/RecoverPassModule/RecoverPassModule.tsx
> +const schema = yup.object().shape({
Better to move to another component

2022-04-25 16:31 UTC, VolodymyrDevico commented on src/components/RecoverPassModule/RecoverPassModule.tsx
> +    console.log({ data });
Remove console log

2022-04-25 16:31 UTC, VolodymyrDevico commented on src/components/RecoverPassModule/RecoverPassModule.tsx
> +    if (recoverIsShown) dispatch(uiActions.toggleForgetPassword());
Merge this conditions

2022-04-25 16:31 UTC, VolodymyrDevico commented on src/components/Auth/AuthStyles.tsx
> +export const StyledButton = styled(Button)({
Maybe you should use theme?

2022-04-27 17:39 UTC, VolodymyrDevico requested changes

2022-04-27 17:39 UTC, VolodymyrDevico commented on src/components/Auth/AuthStyles.tsx
> +  paddingBottom: "4px",
paddingBottom: 4,

2022-04-28 09:08 UTC, turchin-aa reviewed
Good job!

2022-05-01 16:46 UTC, merged