Feature/partners list
cstruchevs/Devico_Project_Client pull request #7
Opened 2022-04-27 16:35 UTC by ntnshpig

2022-04-27 17:41 UTC, VolodymyrDevico requested changes

2022-04-27 17:41 UTC, VolodymyrDevico commented on src/components/PartnersMarquee/PartnersMarquee.tsx
> +          key={index}
Don't use index as key

2022-04-27 17:41 UTC, VolodymyrDevico commented on src/components/PartnersMarquee/PartnersMarquee.tsx
> +    <Marquee style={{ marginTop: "40px" }} pauseOnHover={true} speed={60}>
pauseOnHover

2022-04-28 08:57 UTC, turchin-aa reviewed
Well done!

2022-04-28 10:23 UTC, merged