Feature/sidebar
cstruchevs/Devico_Project_Client pull request #9
Opened 2022-04-29 16:35 UTC by ntnshpig

2022-04-29 17:41 UTC, VolodymyrDevico requested changes

2022-04-29 17:41 UTC, VolodymyrDevico commented on src/App.tsx
> +      <PageRoutes></PageRoutes>
<PageRoutes />

2022-04-29 17:41 UTC, VolodymyrDevico commented on src/components/Sidebar/DesktopSidebar/DesktopSidebar.tsx
> +export default DesktopSidebar
memo(DesktopSidebar)

2022-04-29 17:41 UTC, VolodymyrDevico commented on src/components/Sidebar/MobileSidebar/MobileSidebar.tsx
> +              {upSidebarLinks.map(item => {
item =>(
                  <SidebarButtonStyled {...scrollConfig} to={item.link}>
                    {item.icon}
                    {item.title}
                  </SidebarButtonStyled>
                )

2022-04-29 17:41 UTC, VolodymyrDevico commented on src/components/Sidebar/MobileSidebar/MobileSidebar.tsx
> +                  <SidebarButtonStyled {...scrollConfig} to={item.link}>
key!

2022-04-29 17:41 UTC, VolodymyrDevico commented on src/components/Sidebar/SidebarLinks.tsx
> +        icon: <BusinessOutlinedIcon />,
Icon: BusinessOutlinedIcon
<Icon />

2022-05-01 06:50 UTC, turchin-aa reviewed
This looks good!

2022-05-01 14:04 UTC, cstruchevs approved these changes

2022-05-01 14:12 UTC, merged